#include "type.h"
#include "memlayout.h"
#include "gpio.h"

extern int _sdata, _edata, _sbss, _ebss, _sidata;

extern void _estack(void); // Defined in link.ld

static volatile uint32  _sticks = 0;

static uint32
stexpired(uint32 period)
{
  static uint32 t = 0;
  if(t == 0) t = period + _sticks;
  if(_sticks < t) return 0;
  t = (_sticks - t) > period ? (_sticks + period) : (period + t);
  return 1;
}

int main()
{
  *(RCC_AHB1ENR) |= (0x00000002); // enable GPIO B for LEDs
  gpio_set_mode('B', 7, GPIO_MODE_OUTPUT); // PB7 is blue LED

  int on = 1;
  for(;;){
    if(stexpired(1000)){
      gpio_write('B', 7, on);
      on = !on;
    }
  }

  return 0;
}

void
timerinit(void)
{
  *(SYS_CSR) |= (0x00000007); // enable CLKSOURCE, TICKINT, ENABLE
  // default systick is generated by HSI RC oscillator with 16MHz
  // at here, let's set RVR to 1ms. That means _systick_handler will
  // be triggered every 1ms
  *(SYS_RVR) = (16000000 / 1000) - 1;
  *(SYS_CVR) = 0;
  *(RCC_APB2ENR) |= (1U << 14); // enable SYSCFGEN
}

// Startup code
__attribute__((naked, noreturn)) void _reset(void)
{
  for(int *dst = &_sbss; dst < &_ebss; dst++) *dst = 0;

  for(int *dst = &_sdata, *src = &_sidata; dst < &_edata; dst++, src++)
    *dst = *src;
  
  timerinit();
  main();
  for(;;);
}

void _systick_handler(void)
{
  _sticks++;
}

// 16 standard and 104 STM32-specific handlers
__attribute__((section(".vectors"))) void (*const tab[16+104])(void)={
  _estack, _reset, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, _systick_handler
};
